### ISSUE TITLE
Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by gmoraleslondono** [techeverri/techeverri-cli#1]
![image](https://user-images.githubusercontent.com/20589565/148395099-c415cd85-6227-4f44-b78b-0d4e466798d1.png)

**Comment by techeverri** [comment]
Good catch! 💯 

I think it is because of this line 👇 

https://github.com/techeverri/techeverri-cli/blob/ca12f76e3c0e3b37c78b5ee68d3e029869d08b4c/bin/cli.js#L11

`path.resolve()` returns the path where the CLI is being called from rather than the path where the package is installed which is the one that contains the `bin/card` file
